# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ee/pages/
image: ruby:2.7.0

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install

pages:
  stage: deploy
  script:
    - asciidoctor-pdf index.adoc
  artifacts:
    paths:
    - public
  only:
  - master

pdf:
  stage: deploy
  script:
    - asciidoctor-pdf index.adoc
  artifacts:
    paths:
    - index.pdf
  only:
  - master 
