= gp-documentation-example

Example and guide for documentation

== Overview

We decided to go for centralized and versionized documentation. +
To make it easy to write while coding we went for a markup language. +
Asciidoc seems like a good choice for 'write once publish anywhere' 

== Goal

Write documentation and check it in with the source. +
Have a pipeline run asciidoctor to turn .adoc to .html +
Publish to gitlab pages

== Pipeline

documentation.gitlab-ci.yml +
I borrowed the jekyll pipeline and adapted it for asciidoctor

== Usage

* use/copy the .gitlab-ci.yml & Gemfile from this project
* this builds a gitlab page from an index.adoc document in your source
* the page is deployed under {organisation}.gitlab.io/{repository-name}/


== TODO

* build an asciidoctor image to speed up the process
* add a links section where everyone can put in gitlab page of his repositories -> single point of entry

include::https://gitlab.com/gepaplexx/gp-openshift/-/blob/develop/gp-quotas-and-nw-isolation/README.md[]
